---
#Hash Example
service_name:
  conf:
    os_specific_directory: /opt/MrsDoubtfire
    some_aribitrary_OS_specific_tweak: RedHat



#####Name Spaced Example####
service_name_conf_os_specific_directory: /opt/MrsDoubtfire
service_name_conf_arbitrary_os_additions:
  some_aribitrary_OS_specific_tweak: RedHat
